server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - metrics
          - prometheus
          - health

  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true